type: random_forest
hyper_parameters:
  n_jobs: 8
search_hyper_parameters:
  classifier__estimator__n_estimators: [ 100, 200, 300, 400 ]
  classifier__estimator__max_depth: [ 2, 3, 4 ]
  classifier__estimator__min_samples_leaf: [ 25, 50, 75 ]
